sudo: false

language: python

notifications:
  email:
    - michele@openquake.org
    - gweather@gfz-potsdam.de

python:
 - "3.6"
 - "3.8"

addons:
  apt:
    packages:
    - git

install:
  # Check if the same branch exists on 'oq-engine'
  - if [ "$TRAVIS_PULL_REQUEST_BRANCH" != "" ]; then BRANCH=$TRAVIS_PULL_REQUEST_BRANCH; else BRANCH=$TRAVIS_BRANCH; fi
  - if [ "$(git ls-remote --heads https://github.com/gem/oq-engine.git ${BRANCH})" == "" ]; then
      BRANCH='master';
    fi;
  # Clone 'oq-engine'
  - git clone -q -b $BRANCH --depth=1 https://github.com/gem/oq-engine.git && echo "Running against oq-engine/${BRANCH}"
  # Make sure pip is up-to-date and has support for wheels
  - pip -q install -U pip
  # Install oq-engine dependencies
  - pip install -r oq-engine/requirements-py38-linux64.txt
  - pip install -e oq-engine/
  - pip install -e .

script:
  - pytest -vsx tests/hazard/conditional_simulation_test.py
  - pytest -vsx tests/intensity_measures_test.py
  - pytest -vsx tests/trellis/trellis_test.py
  - pytest -vsx tests/parsers/asa_parser_test.py
  - pytest -vsx tests/parsers/esm_flatfile_parser_test.py
  - pytest -vsx tests/residuals/residuals_test.py
