sudo: false

language: python

python:
 - "2.7"

addons:
  apt:
    packages:
    - git

env:
    global:
    - PYTHONPATH=$TRAVIS_BUILD_DIR/oq-hazardlib:$TRAVIS_BUILD_DIR/oq-engine

install:
  # Clone oq-hazardlib and oq-engine
  - git clone --depth=1 https://github.com/gem/oq-hazardlib.git
  - git clone --depth=1 https://github.com/gem/oq-engine.git
  # Make sure pip is up-to-date and has support for wheels
  - pip install -U pip
  # Install oq-hazardlib and oq-engine dependencies
  - pip install -r oq-hazardlib/requirements-py27-linux64.txt
  - pip install -r oq-engine/requirements-py27-linux64.txt
  # Install HMTK extra dependencies
  - pip install -r requirements-py27-linux64.txt
  - pip install -e oq-hazardlib/ && pip install oq-engine/
  - pip install .

script:
  - nosetests -vx tests
