sudo: false

language: python

python:
 - "2.7"

addons:
  apt:
    packages:
    - git

install:
  # Clone oq-engine
  - git clone --depth=1 https://github.com/gem/oq-engine.git
  # Make sure pip is up-to-date and has support for wheels
  - pip install -U pip
  # Install oq-engine dependencies
  - pip install -r oq-engine/requirements-py27-linux64.txt
  - pip install -e oq-engine/
  # Install HMTK extra dependencies
  - pip install -r requirements-py27-linux64.txt
  - pip install -e .

script:
  - nosetests -vx tests
